name = "hoyolab-embed-fixer"
main = "src/index.ts"
compatibility_date = "2024-12-10"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

# Uncomment to add custom domain
# routes = [
#   { pattern = "fxhyl.yourdomain.com", custom_domain = true }
# ]